# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('city', models.CharField(max_length=200)),
                ('favorite', models.CharField(choices=[('', '\u041b\u044e\u0431\u0438\u043c\u044b\u0439 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442'), ('akvarek', '\u0410\u043a\u0432\u0430\u0440\u0435\u043b\u044c\u043d\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('akril', '\u0410\u043a\u0440\u0438\u043b\u043e\u0432\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('oil', '\u041c\u0430\u0441\u043b\u044f\u043d\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('akp', '\u041a\u0430\u043f\u0438\u043b\u043b\u044f\u0440\u043d\u044b\u0435 \u0440\u0443\u0447\u043a\u0438'), ('color', '\u0426\u0432\u0435\u0442\u043d\u044b\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u0438'), ('mono', '\u041c\u043e\u043d\u043e\u0445\u0440\u043e\u043c\u043d\u044b\u0435 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b')], max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('age', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(default='', max_length=2000)),
                ('docfile', models.FileField(default='', upload_to='Jurys')),
                ('Post', models.CharField(default='', max_length=2000)),
                ('Post2', tinymce.models.HTMLField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('logo', models.FileField(upload_to='logoPartner')),
                ('text2', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('logo', models.FileField(upload_to='logoSponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Task_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task1')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task2')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task4')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task4')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task5')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task6')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task7')),
                ('visible', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('artist1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_is_it', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
