# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('favorite', models.CharField(choices=[('Unseen', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), ('Approved', '\u0423\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043e'), ('Denide', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043e')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('logo', models.FileField(upload_to='logoPartner')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('logo', models.FileField(upload_to='logoSponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Task_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task1')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task2')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task4')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task4')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task5')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task6')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Task_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='Task7')),
                ('visible', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_is_it', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bh2017.Artist')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
