# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0002_auto_20170311_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='text2',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
