# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0003_auto_20170312_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='favorite',
            field=models.CharField(choices=[('', '\u041b\u044e\u0431\u0438\u043c\u044b\u0439 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442'), ('Unseen', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), ('Approved', '\u0423\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043e'), ('Denide', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043e')], max_length=200),
        ),
    ]
