# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0005_auto_20170313_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='favorite',
            field=models.CharField(choices=[('', '\u041b\u044e\u0431\u0438\u043c\u044b\u0439 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442'), ('akvarek', '\u0410\u043a\u0432\u0430\u0440\u0435\u043b\u044c\u043d\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('akril', '\u0410\u043a\u0440\u0438\u043b\u043e\u0432\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('oil', '\u041c\u0430\u0441\u043b\u044f\u043d\u044b\u0435 \u043a\u0440\u0430\u0441\u043a\u0438'), ('akp', '\u041a\u0430\u043f\u0438\u043b\u043b\u044f\u0440\u043d\u044b\u0435 \u0440\u0443\u0447\u043a\u0438'), ('color', '\u0426\u0432\u0435\u0442\u043d\u044b\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u0438'), ('mono', '\u041c\u043e\u043d\u043e\u0445\u0440\u043d\u043e\u043c\u043d\u044b\u0435 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b')], max_length=200),
        ),
    ]
