# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0007_auto_20170316_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='Post2',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
