# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0008_jury_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
