# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0010_auto_20170322_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Tasks',
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.DeleteModel(
            name='Task3',
        ),
        migrations.DeleteModel(
            name='Task4',
        ),
        migrations.DeleteModel(
            name='Task5',
        ),
        migrations.DeleteModel(
            name='Task6',
        ),
        migrations.DeleteModel(
            name='Task7',
        ),
    ]
