# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bh2017', '0011_auto_20170322_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_1',
            name='art',
        ),
        migrations.AddField(
            model_name='task_1',
            name='artist',
            field=models.OneToOneField(blank=True, default='0 14020', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
