# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0012_auto_20170323_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_1',
            name='artist',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
