# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bh2017', '0013_auto_20170323_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_1',
            old_name='artist',
            new_name='artist1',
        ),
    ]
