# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bh2017', '0014_auto_20170323_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_2',
            name='art',
        ),
        migrations.RemoveField(
            model_name='task_3',
            name='art',
        ),
        migrations.RemoveField(
            model_name='task_4',
            name='art',
        ),
        migrations.RemoveField(
            model_name='task_5',
            name='art',
        ),
        migrations.RemoveField(
            model_name='task_6',
            name='art',
        ),
        migrations.RemoveField(
            model_name='task_7',
            name='art',
        ),
        migrations.AddField(
            model_name='task_2',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_3',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_4',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_5',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_6',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_7',
            name='artist1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
